FROM python:3.11

WORKDIR /app

COPY neurons /app/neurons
COPY requirements.txt /app

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

EXPOSE 8000

CMD ["python", "neurons/validator_api.py"]