FROM python:3.11

WORKDIR /app

COPY neurons /app/neurons
COPY requirements.txt /app

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Install curl for downloading Foundry
RUN apt-get update && apt-get install -y curl

# Install Foundry
RUN curl -L https://foundry.paradigm.xyz | bash
RUN foundryup

CMD ["python", "neurons/validator.py"]