FROM python:3.11

WORKDIR /app

COPY neurons /app/neurons
COPY requirements.txt /app

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Install Foundry
RUN curl -L https://foundry.paradigm.xyz | bash
ENV PATH="/root/.foundry/bin:$PATH"
RUN ~/.foundry/bin/foundryup

# Set PYTHONPATH to include the current directory
ENV PYTHONPATH="/app:$PYTHONPATH"

CMD ["python", "-m", "neurons.validator"]